// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOFP9vXRzk8vo9BG-razEhuI5vy8p9zw',
    appId: '1:907119109987:web:133662499d59fdcd3e1556',
    messagingSenderId: '907119109987',
    projectId: 'school-manage-98ee0',
    authDomain: 'school-manage-98ee0.firebaseapp.com',
    storageBucket: 'school-manage-98ee0.firebasestorage.app',
    measurementId: 'G-FT4PHD5NJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXYLipeLBAJprvz4GzeYUfskPNFd4uEU',
    appId: '1:907119109987:android:15db180e64cb34be3e1556',
    messagingSenderId: '907119109987',
    projectId: 'school-manage-98ee0',
    storageBucket: 'school-manage-98ee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcXFSzr-6ADchIs6fq_iXX9nhE1g5e40',
    appId: '1:907119109987:ios:3f4f5b6087bd968e3e1556',
    messagingSenderId: '907119109987',
    projectId: 'school-manage-98ee0',
    storageBucket: 'school-manage-98ee0.firebasestorage.app',
    iosBundleId: 'com.example.schoolSatfWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVcXFSzr-6ADchIs6fq_iXX9nhE1g5e40',
    appId: '1:907119109987:ios:3f4f5b6087bd968e3e1556',
    messagingSenderId: '907119109987',
    projectId: 'school-manage-98ee0',
    storageBucket: 'school-manage-98ee0.firebasestorage.app',
    iosBundleId: 'com.example.schoolSatfWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEOFP9vXRzk8vo9BG-razEhuI5vy8p9zw',
    appId: '1:907119109987:web:61391744fa2fec3c3e1556',
    messagingSenderId: '907119109987',
    projectId: 'school-manage-98ee0',
    authDomain: 'school-manage-98ee0.firebaseapp.com',
    storageBucket: 'school-manage-98ee0.firebasestorage.app',
    measurementId: 'G-1TE1BRTMR6',
  );
}
